package com.example.pcceobservability.service;

import com.example.pcceobservability.model.ServerLogTarget;
import com.example.pcceobservability.model.SupportCapability;
import com.example.pcceobservability.model.UpdateServerLogTargetRequest;
import java.util.ArrayList;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

@Service
public class SupportCapabilityService {

    private final List<ServerLogTarget> serverLogTargets = new ArrayList<>(List.of(
            new ServerLogTarget("ICM_Router", "vswsitrgr01", "ICM Router / Rogger logs", "Windows share / agent / SIEM", false),
            new ServerLogTarget("ICM_Logger", "vswsitaw01", "Logger, AW, HDS and SQL logs", "Windows share / agent / SIEM", false),
            new ServerLogTarget("CTI_Server", "vswsitpg01", "CTI Server logs", "Windows share / agent / SIEM", false),
            new ServerLogTarget("PG_CUCM", "vswsitpg01", "CUCM PG logs", "Windows share / agent / SIEM", false),
            new ServerLogTarget("PG_CVP", "vswsitpg01", "CVP PG logs", "Windows share / agent / SIEM", false),
            new ServerLogTarget("CVP_CallServer", "vswsitcvp01", "CVP Call Server and VXML/Tomcat logs", "SFTP / agent / SIEM", false),
            new ServerLogTarget("CVP_ReportingServer", "vswsitcvpr01", "CVP Reporting / Informix logs", "SFTP / agent / SIEM", false),
            new ServerLogTarget("Finesse", "vssitfin01", "Finesse Tomcat/application logs", "SFTP / agent / SIEM", false),
            new ServerLogTarget("CUIC", "vssitcuic01", "CUIC, Live Data and IDS logs", "SFTP / agent / SIEM", false),
            new ServerLogTarget("VVB", "vssitvvb01", "VVB application and voice browser logs", "SFTP / agent / SIEM", false),
            new ServerLogTarget("CUCM", "vssitcucm01", "CUCM syslog/RTMT logs", "Syslog / RTMT / SIEM", false)));

    public List<SupportCapability> smtpCapabilities() {
        return List.of(
                new SupportCapability("Email Alerts", "Send critical component/data alerts by email", "Config required", "Configure SMTP host, sender, recipients, and minimum severity"),
                new SupportCapability("SMS Alerts", "Send critical alerts through D-Tech SMS microgateway", "Config required", "Configure SMS URL, Basic Authorization, User-Agent, recipients, and SMS severity threshold"),
                new SupportCapability("Threshold Routing", "Use different thresholds for webhook/email and SMS", "Available", "Global minimum-severity controls webhook/email; sms-minimum-severity controls SMS"),
                new SupportCapability("Alert Storm Guard", "Limit SMS messages generated by each assessment", "Available", "Use sms-max-alerts-per-assessment"),
                new SupportCapability("Operations Summary", "Send daily banking operations summary", "Planned", "Use scheduled report export after CUIC mappings are finalized"));
    }

    public List<SupportCapability> spogCapabilities() {
        return List.of(
                new SupportCapability("Graceful Operations", "Maintenance mode and alert suppression", "Available", "Use Operations API maintenance endpoint"),
                new SupportCapability("Graceful Operations", "Graceful Spring Boot shutdown", "Admin gated", "Enable actuator shutdown only in approved maintenance window"),
                new SupportCapability("Log Collection", "Collect application logs", "Available", "Use Recent App Logs and monitoring/logs endpoint"),
                new SupportCapability("PCCE Log Monitoring", "Monitor Router/Logger/PG/CVP/Finesse/CUIC/VVB/CUCM logs", "Config required", "Enable server log targets and connect Windows share, SFTP, syslog, SIEM, or an agent"),
                new SupportCapability("SPOG", "Single operational view across DB, APIs, components, alerts, logs", "Available", "Use System Health, Spring Boot App, PCCE Integration tabs"),
                new SupportCapability("RTMT Extension", "CPU/memory/disk/service/process counters", "Config required", "Integrate SNMP/WMI/JMX/enterprise monitoring source"));
    }

    public List<ServerLogTarget> serverLogTargets() {
        return List.copyOf(serverLogTargets);
    }

    public ServerLogTarget updateServerLogTarget(String component, UpdateServerLogTargetRequest request) {
        if (!StringUtils.hasText(component)) {
            throw new IllegalArgumentException("component is required");
        }
        for (int index = 0; index < serverLogTargets.size(); index++) {
            ServerLogTarget current = serverLogTargets.get(index);
            if (current.component().equalsIgnoreCase(component)) {
                ServerLogTarget updated = merge(current, request);
                serverLogTargets.set(index, updated);
                return updated;
            }
        }
        ServerLogTarget created = new ServerLogTarget(
                component,
                request == null || request.host() == null ? "" : request.host(),
                request == null || request.logPath() == null ? "" : request.logPath(),
                request == null || request.collectionMethod() == null ? "agent / SIEM" : request.collectionMethod(),
                request != null && Boolean.TRUE.equals(request.enabled()));
        serverLogTargets.add(created);
        return created;
    }

    private ServerLogTarget merge(ServerLogTarget current, UpdateServerLogTargetRequest request) {
        if (request == null) {
            return current;
        }
        return new ServerLogTarget(
                current.component(),
                request.host() == null ? current.host() : request.host(),
                request.logPath() == null ? current.logPath() : request.logPath(),
                request.collectionMethod() == null ? current.collectionMethod() : request.collectionMethod(),
                request.enabled() == null ? current.enabled() : request.enabled());
    }
}
