server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

pcce:
  operations:
    scheduled-assessment-enabled: false
    assessment-fixed-delay-ms: 300000

  datasources:
    aw:
      hikari:
        initialization-fail-timeout: -1
        maximum-pool-size: 2
    hds:
      hikari:
        initialization-fail-timeout: -1
        maximum-pool-size: 2
    cvp-reporting:
      hikari:
        initialization-fail-timeout: -1
        maximum-pool-size: 2
