CREATE TABLE IF NOT EXISTS project_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sort_order INTEGER NOT NULL,
    topic VARCHAR(100) NOT NULL,
    task VARCHAR(500) NOT NULL,
    priority VARCHAR(30) NOT NULL,
    priority_num INTEGER,
    status VARCHAR(40) NOT NULL,
    resource VARCHAR(300) NOT NULL,
    start_text VARCHAR(40),
    finish_text VARCHAR(40),
    duration INTEGER,
    pct INTEGER NOT NULL,
    comments VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_project_tasks_topic ON project_tasks(topic);
CREATE INDEX IF NOT EXISTS idx_project_tasks_status ON project_tasks(status);
CREATE INDEX IF NOT EXISTS idx_project_tasks_priority ON project_tasks(priority);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key VARCHAR(160) PRIMARY KEY,
    setting_value TEXT,
    secret BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_users (
    username VARCHAR(160) PRIMARY KEY,
    password_hash VARCHAR(300) NOT NULL,
    display_name VARCHAR(200),
    agent_id VARCHAR(80),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_user_roles (
    username VARCHAR(160) NOT NULL,
    role_name VARCHAR(80) NOT NULL,
    PRIMARY KEY (username, role_name),
    CONSTRAINT fk_app_user_roles_user FOREIGN KEY (username) REFERENCES app_users(username) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS app_user_teams (
    username VARCHAR(160) NOT NULL,
    team_name VARCHAR(160) NOT NULL,
    PRIMARY KEY (username, team_name),
    CONSTRAINT fk_app_user_teams_user FOREIGN KEY (username) REFERENCES app_users(username) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS app_role_permissions (
    role_name VARCHAR(80) NOT NULL,
    permission_name VARCHAR(120) NOT NULL,
    PRIMARY KEY (role_name, permission_name)
);

CREATE TABLE IF NOT EXISTS server_log_targets (
    component VARCHAR(120) PRIMARY KEY,
    host VARCHAR(200),
    log_path VARCHAR(500),
    collection_method VARCHAR(200),
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor VARCHAR(160),
    action VARCHAR(160) NOT NULL,
    target VARCHAR(300),
    details TEXT
);
