CREATE TABLE IF NOT EXISTS agent_skill_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id VARCHAR(160) NOT NULL,
    agent_name VARCHAR(240),
    team_name VARCHAR(160),
    skill_group VARCHAR(240) NOT NULL,
    proficiency INTEGER,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    source VARCHAR(80) NOT NULL DEFAULT 'APP',
    notes VARCHAR(1000),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_skill_assignment UNIQUE (agent_id, skill_group)
);

CREATE INDEX IF NOT EXISTS idx_agent_skill_assignments_agent ON agent_skill_assignments(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_skill_assignments_skill ON agent_skill_assignments(skill_group);
CREATE INDEX IF NOT EXISTS idx_agent_skill_assignments_team ON agent_skill_assignments(team_name);

CREATE TABLE IF NOT EXISTS ivr_feature_toggles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name VARCHAR(240) NOT NULL,
    feature_key VARCHAR(120) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    min_severity VARCHAR(40) DEFAULT 'WARNING',
    config_value VARCHAR(1000),
    notes VARCHAR(1000),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ivr_feature UNIQUE (app_name, feature_key)
);

CREATE INDEX IF NOT EXISTS idx_ivr_feature_toggles_app ON ivr_feature_toggles(app_name);
